import crypto from "crypto";

let generatedKey: string | null = null;
let isAutoGenerated = false;

export function getApiKey(): string {
  const envKey = process.env["PROXY_API_KEY"];
  if (envKey) {
    return envKey;
  }
  if (!generatedKey) {
    generatedKey = crypto.randomBytes(24).toString("hex");
    isAutoGenerated = true;
    console.log(`\n[AI Gateway] No PROXY_API_KEY set — auto-generated key: ${generatedKey}\n`);
  }
  return generatedKey;
}

export function getKeyInfo(): { key: string; autoGenerated: boolean } {
  return {
    key: getApiKey(),
    autoGenerated: isAutoGenerated || !process.env["PROXY_API_KEY"],
  };
}
