import { Router } from "express";
import { getKeyInfo } from "../lib/keyManager";

const router = Router();

router.get("/setup-key", (_req, res) => {
  const { key, autoGenerated } = getKeyInfo();
  res.json({ key, autoGenerated });
});

export default router;
